PRAGMA FOREIGN_KEYS = ON;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
    ID_USER INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    TYPE VARCHAR(255) NOT NULL CHECK (TYPE IN ('STUDENT', 'TUTOR', 'ADMIN'))
);

INSERT INTO USERS(USERNAME, PASSWORD, EMAIL, TYPE) VALUES
('martim', '$2y$10$KhO3NI22.eu0Nj4XOmO3n.hH/ILLRxsvAlxei.h40Y9Qyi1XlVKXO ', 'martim@gmail.com', 'ADMIN');


DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT(
    ID_STUDENT VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PROFILE_IMAGE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIMARY KEY (ID_STUDENT),
    FOREIGN KEY (ID_STUDENT) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);




DROP TABLE IF EXISTS TUTOR;

CREATE TABLE TUTOR(
    ID_TUTOR VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PROFILE_IMAGE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIMARY KEY (ID_TUTOR),
    FOREIGN KEY (ID_TUTOR) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);


CREATE TABLE ADMIN(
    ID_ADMIN VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PROFILE_IMAGE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIMARY KEY (ID_ADMIN),
    FOREIGN KEY (ID_ADMIN) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

INSERT INTO ADMIN(ID_ADMIN, NAME, DATE_OF_BIRTH, PROFILE_IMAGE, DESCRIPTION) VALUES
('martim', 'Martim', '2005-12-09', 'martim.png', 'Hi! I am Martim.');


DROP TABLE IF EXISTS STUDENT_TUTOR;

CREATE TABLE STUDENT_TUTOR(
    STUDENT VARCHAR(255) REFERENCES STUDENT(ID_STUDENT) ON DELETE CASCADE,
    TUTOR VARCHAR(255) REFERENCES TUTOR(ID_TUTOR) ON DELETE CASCADE,
    PRIMARY KEY (STUDENT, TUTOR)
);



DROP TABLE IF EXISTS REQUEST;

CREATE TABLE REQUEST(
    ID_REQUEST INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCEPTED BOOLEAN NOT NULL DEFAULT FALSE,
    STUDENT VARCHAR(255) REFERENCES STUDENT(ID_STUDENT) ON DELETE CASCADE,
    TUTOR VARCHAR(255) REFERENCES TUTOR(ID_TUTOR) ON DELETE CASCADE,
    REQUEST_DATE DATE NOT NULL,
    DATE_ACCEPTED DATE,
    MESSAGE TEXT,
    FOREIGN KEY (STUDENT) REFERENCES STUDENT(ID_STUDENT) ON DELETE CASCADE,
    FOREIGN KEY (TUTOR) REFERENCES TUTOR(ID_TUTOR) ON DELETE CASCADE,
    UNIQUE (STUDENT, TUTOR)
);

DROP TABLE IF EXISTS MESSAGE;

CREATE TABLE MESSAGE(
    ID_MESSAGE INTEGER PRIMARY KEY AUTOINCREMENT,
    SENDER VARCHAR(255) NOT NULL,
    RECEIVER VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER) REFERENCES USERS(USERNAME) ON DELETE CASCADE,
    FOREIGN KEY (RECEIVER) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);


DROP TABLE IF EXISTS RATING;

CREATE TABLE RATING (
    ID_RATING INTEGER PRIMARY KEY AUTOINCREMENT,
    TUTOR VARCHAR(255) NOT NULL,
    STUDENT VARCHAR(255) NOT NULL,
    RATING INTEGER CHECK (
        RATING >= 0 AND 
        RATING <= 5 AND 
        (RATING * 10) % 5 = 0
    ),
    COMMENTARY TEXT,
    FOREIGN KEY (STUDENT) REFERENCES STUDENT(ID_STUDENT) ON DELETE CASCADE,
    FOREIGN KEY (TUTOR) REFERENCES TUTOR(ID_TUTOR) ON DELETE CASCADE
);


DROP TABLE IF EXISTS LANGUAGE;

CREATE TABLE LANGUAGE(
    DESIGNATION VARCHAR(255) NOT NULL PRIMARY KEY
);

INSERT INTO LANGUAGE (DESIGNATION) VALUES
('English'),
('Spanish'),
('French'),
('German'),
('Mandarin'),
('Japanese'),
('Portuguese'),
('Russian'),
('Arabic'),
('Italian');


DROP TABLE IF EXISTS STUDENT_LANGUAGE;

CREATE TABLE STUDENT_LANGUAGE(
    STUDENT VARCHAR(225) REFERENCES STUDENT(ID_STUDENT) ON DELETE CASCADE,
    LANGUAGE VARCHAR(255) REFERENCES LANGUAGE(DESIGNATION) ON DELETE CASCADE,
    PRIMARY KEY (STUDENT, LANGUAGE)
);



DROP TABLE IF EXISTS TUTOR_LANGUAGE;

CREATE TABLE TUTOR_LANGUAGE(
    TUTOR VARCHAR(225) REFERENCES TUTOR(ID_TUTOR) ON DELETE CASCADE,
    LANGUAGE VARCHAR(255) REFERENCES LANGUAGE(DESIGNATION) ON DELETE CASCADE,
    PRIMARY KEY (TUTOR, LANGUAGE)
);



DROP TABLE IF EXISTS SUBJECT;

CREATE TABLE SUBJECT(
    DESIGNATION VARCHAR(255) NOT NULL PRIMARY KEY
);

INSERT INTO SUBJECT (DESIGNATION) VALUES
('Portuguese'),
('Mathematics'),
('English'),
('Social and Environmental Studies'),
('History and Geography of Portugal'),
('Natural Sciences'),
('French'),
('Spanish'),
('History'),
('Geography'),
('Physics and Chemistry'),
('German'),
('Philosophy'),
('Biology and Geology'),
('Descriptive Geometry'),
('Economics'),
('Mathematics Applied to Social Sciences'),
('Drawing'),
('History and Culture of the Arts');


DROP TABLE IF EXISTS STUDENT_SUBJECT;

CREATE TABLE STUDENT_SUBJECT(
    STUDENT VARCHAR(255) REFERENCES STUDENT(ID_STUDENT) ON DELETE CASCADE,
    SUBJECT VARCHAR(255) REFERENCES SUBJECT(DESIGNATION) ON DELETE CASCADE,
    STUDENT_LEVEL VARCHAR(255) REFERENCES STUDENT_LEVEL(DESIGNATION) ON DELETE CASCADE,
    PRIMARY KEY (STUDENT, SUBJECT, STUDENT_LEVEL)
);


DROP TABLE IF EXISTS TUTOR_SUBJECT;

CREATE TABLE TUTOR_SUBJECT(
    TUTOR VARCHAR(255) REFERENCES TUTOR(ID_TUTOR) ON DELETE CASCADE,
    SUBJECT VARCHAR(255) REFERENCES SUBJECT(DESIGNATION) ON DELETE CASCADE,
    TUTOR_LEVEL VARCHAR(255) REFERENCES TUTOR_LEVEL(DESIGNATION) ON DELETE CASCADE,
    PRIMARY KEY (TUTOR, SUBJECT, TUTOR_LEVEL)
);


DROP TABLE IF EXISTS TUTOR_LEVEL;

CREATE TABLE TUTOR_LEVEL(
    DESIGNATION VARCHAR(255) NOT NULL PRIMARY KEY
);

INSERT INTO TUTOR_LEVEL (DESIGNATION) VALUES
('Grade 1-4'),
('Grade 5-6'),
('Grade 7-9'),
('Grade 10-12');

DROP TABLE IF EXISTS STUDENT_LEVEL;

CREATE TABLE STUDENT_LEVEL(
    DESIGNATION VARCHAR(255) NOT NULL PRIMARY KEY
);

INSERT INTO STUDENT_LEVEL (DESIGNATION) VALUES
('Grade 1'),
('Grade 2'),
('Grade 3'),
('Grade 4'),
('Grade 5'),
('Grade 6'),
('Grade 7'),
('Grade 8'),
('Grade 9'),
('Grade 10'),
('Grade 11'),
('Grade 12');

